package com.company.database;

/**
 * Generated by Protege (http://protege.stanford.edu).
 * Source Class: Car
 *
 * @version generated on Mon Apr 18 14:26:55 MSD 2016
 */
public interface Car {

    // Slot marka

    String getMarka();

    boolean hasMarka();

    void setMarka(String newMarka);


    // Slot model

    String getModel();

    boolean hasModel();

    void setModel(String newModel);


    // Slot power

    int getPower();

    boolean hasPower();

    void setPower(int newPower);

    void delete();
}
