package com.company.database;

/**
 * Generated by Protege (http://protege.stanford.edu).
 * Source Class: City
 *
 * @version generated on Mon Apr 18 14:26:55 MSD 2016
 */
public interface City {

    // Slot Koeef

    float getKoeef();

    boolean hasKoeef();

    void setKoeef(float newKoeef);


    // Slot cityName

    String getCityName();

    boolean hasCityName();

    void setCityName(String newCityName);

    void delete();
}
