package com.company.database;

/**
 * Generated by Protege (http://protege.stanford.edu).
 * Source Class: DateDTP
 *
 * @version generated on Mon Apr 18 14:26:55 MSD 2016
 */
public interface DateDTP {

    // Slot date

    String getDate();

    boolean hasDate();

    void setDate(String newDate);

    void delete();
}
