package com.company.database;

/**
 * Generated by Protege (http://protege.stanford.edu).
 * Source Class: Koeefis
 *
 * @version generated on Mon Apr 18 14:26:55 MSD 2016
 */
public interface Koeefis {

    void delete();
}
