package com.company.database;

/**
 * Generated by Protege (http://protege.stanford.edu).
 * Source Class: KoefKVS
 *
 * @version generated on Mon Apr 18 14:26:55 MSD 2016
 */
public interface KoefKVS extends Koeefis {

    // Slot ageKoef

    int getAgeKoef();

    boolean hasAgeKoef();

    void setAgeKoef(int newAgeKoef);


    // Slot stajKoef

    int getStajKoef();

    boolean hasStajKoef();

    void setStajKoef(int newStajKoef);


    // Slot value

    float getValue();

    boolean hasValue();

    void setValue(float newValue);

    void delete();
}
