package com.company.database;

/**
 * Generated by Protege (http://protege.stanford.edu).
 * Source Class: KoefKM
 *
 * @version generated on Mon Apr 18 14:26:55 MSD 2016
 */
public interface KoefKM extends Koeefis {

    // Slot power

    int getPower();

    boolean hasPower();

    void setPower(int newPower);


    // Slot value

    float getValue();

    boolean hasValue();

    void setValue(float newValue);

    void delete();
}
