package com.company.database;

/**
 * Generated by Protege (http://protege.stanford.edu).
 * Source Class: KoefKS
 *
 * @version generated on Mon Apr 18 14:26:55 MSD 2016
 */
public interface KoefKS extends Koeefis {

    // Slot klassKS

    int getKlassKS();

    boolean hasKlassKS();

    void setKlassKS(int newKlassKS);


    // Slot value

    float getValue();

    boolean hasValue();

    void setValue(float newValue);

    void delete();
}
