package com.company.database;

/**
 * Generated by Protege (http://protege.stanford.edu).
 * Source Class: KoefKBM
 *
 * @version generated on Mon Apr 18 14:26:55 MSD 2016
 */
public interface KoefKBM extends Koeefis {

    // Slot KBM0

    int getKBM0();

    boolean hasKBM0();

    void setKBM0(int newKBM0);


    // Slot KBM1

    int getKBM1();

    boolean hasKBM1();

    void setKBM1(int newKBM1);


    // Slot KBM2

    int getKBM2();

    boolean hasKBM2();

    void setKBM2(int newKBM2);


    // Slot KBM3

    int getKBM3();

    boolean hasKBM3();

    void setKBM3(int newKBM3);


    // Slot KBM4

    int getKBM4();

    boolean hasKBM4();

    void setKBM4(int newKBM4);


    // Slot klassKBM

    int getKlassKBM();

    boolean hasKlassKBM();

    void setKlassKBM(int newKlassKBM);


    // Slot value

    float getValue();

    boolean hasValue();

    void setValue(float newValue);

    void delete();
}
