package com.company.database;

import com.company.database.impl.*;
import edu.stanford.smi.protege.code.generator.wrapping.OntologyJavaMappingUtil;

/**
 * Generated by Protege (http://protege.stanford.edu).
 *
 * @version generated on Mon Apr 18 14:26:55 MSD 2016
 */
public class OntologyJavaMapping {

    public static void initMap() {
        OntologyJavaMappingUtil.add("Car", Car.class, DefaultCar.class);
        OntologyJavaMappingUtil.add("City", City.class, DefaultCity.class);
        OntologyJavaMappingUtil.add("DateDTP", DateDTP.class, DefaultDateDTP.class);
        OntologyJavaMappingUtil.add("Human", Human.class, DefaultHuman.class);
        OntologyJavaMappingUtil.add("Koeefis", Koeefis.class, DefaultKoeefis.class);
        OntologyJavaMappingUtil.add("KoefChanceDTP", KoefChanceDTP.class, DefaultKoefChanceDTP.class);
        OntologyJavaMappingUtil.add("KoefKBM", KoefKBM.class, DefaultKoefKBM.class);
        OntologyJavaMappingUtil.add("KoefKM", KoefKM.class, DefaultKoefKM.class);
        OntologyJavaMappingUtil.add("KoefKS", KoefKS.class, DefaultKoefKS.class);
        OntologyJavaMappingUtil.add("KoefKVS", KoefKVS.class, DefaultKoefKVS.class);
        OntologyJavaMappingUtil.add("StrahCompany", StrahCompany.class, DefaultStrahCompany.class);
    }
}
