package com.company.database;

/**
 * Generated by Protege (http://protege.stanford.edu).
 * Source Class: StrahCompany
 *
 * @version generated on Mon Apr 18 14:26:55 MSD 2016
 */
public interface StrahCompany {

    // Slot basisStavka

    int getBasisStavka();

    boolean hasBasisStavka();

    void setBasisStavka(int newBasisStavka);


    // Slot companyName

    String getCompanyName();

    boolean hasCompanyName();

    void setCompanyName(String newCompanyName);

    void delete();
}
