package com.company.database.impl;

import edu.stanford.smi.protege.code.generator.wrapping.AbstractWrappedInstance;
import edu.stanford.smi.protege.model.*;
import com.company.database.KoefChanceDTP;
import com.company.database.*;

/**
 * Generated by Protege (http://protege.stanford.edu).
 * Source Class: KoefChanceDTP
 *
 * @version generated on Mon Apr 18 14:26:55 MSD 2016
 */
public class DefaultKoefChanceDTP extends DefaultKoeefis
         implements KoefChanceDTP {

    public DefaultKoefChanceDTP(Instance instance) {
        super(instance);
    }


    public DefaultKoefChanceDTP() {
    }

    // Slot ageKoef

    public int getAgeKoef() {
        java.lang.Integer value = (java.lang.Integer) getWrappedProtegeInstance().getOwnSlotValue(getAgeKoefSlot());
        return value == null ? null :
            (java.lang.Integer) value.intValue();
    }


    public Slot getAgeKoefSlot() {
        final String name = "ageKoef";
        return getKnowledgeBase().getSlot(name);
    }


    public boolean hasAgeKoef() {
        return hasSlotValues(getAgeKoefSlot());
    }


    public void setAgeKoef(int newAgeKoef) {
        setSlotValue(getAgeKoefSlot(), new java.lang.Integer(newAgeKoef));
    }

    // Slot stajKoef

    public int getStajKoef() {
        java.lang.Integer value = (java.lang.Integer) getWrappedProtegeInstance().getOwnSlotValue(getStajKoefSlot());
        return value == null ? null :
            (java.lang.Integer) value.intValue();
    }


    public Slot getStajKoefSlot() {
        final String name = "stajKoef";
        return getKnowledgeBase().getSlot(name);
    }


    public boolean hasStajKoef() {
        return hasSlotValues(getStajKoefSlot());
    }


    public void setStajKoef(int newStajKoef) {
        setSlotValue(getStajKoefSlot(), new java.lang.Integer(newStajKoef));
    }

    // Slot value

    public float getValue() {
        java.lang.Float value = (java.lang.Float) getWrappedProtegeInstance().getOwnSlotValue(getValueSlot());
        return value == null ? null :
            (java.lang.Float) value.floatValue();
    }


    public Slot getValueSlot() {
        final String name = "value";
        return getKnowledgeBase().getSlot(name);
    }


    public boolean hasValue() {
        return hasSlotValues(getValueSlot());
    }


    public void setValue(float newValue) {
        setSlotValue(getValueSlot(), new java.lang.Float(newValue));
    }
}
