package com.company.database.impl;

import edu.stanford.smi.protege.code.generator.wrapping.AbstractWrappedInstance;
import edu.stanford.smi.protege.model.*;
import com.company.database.Koeefis;
import com.company.database.*;

/**
 * Generated by Protege (http://protege.stanford.edu).
 * Source Class: Koeefis
 *
 * @version generated on Mon Apr 18 14:26:55 MSD 2016
 */
public class DefaultKoeefis extends AbstractWrappedInstance
         implements Koeefis {

    public DefaultKoeefis(Instance instance) {
        super(instance);
    }


    public DefaultKoeefis() {
    }
}
