package com.company.database.impl;

import edu.stanford.smi.protege.code.generator.wrapping.AbstractWrappedInstance;
import edu.stanford.smi.protege.model.*;
import com.company.database.DateDTP;
import com.company.database.*;

/**
 * Generated by Protege (http://protege.stanford.edu).
 * Source Class: DateDTP
 *
 * @version generated on Mon Apr 18 14:26:55 MSD 2016
 */
public class DefaultDateDTP extends AbstractWrappedInstance
         implements DateDTP {

    public DefaultDateDTP(Instance instance) {
        super(instance);
    }


    public DefaultDateDTP() {
    }

    // Slot date

    public String getDate() {
        return (String) getWrappedProtegeInstance().getOwnSlotValue(getDateSlot());
    }


    public Slot getDateSlot() {
        final String name = "date";
        return getKnowledgeBase().getSlot(name);
    }


    public boolean hasDate() {
        return hasSlotValues(getDateSlot());
    }


    public void setDate(String newDate) {
        setSlotValue(getDateSlot(), newDate);
    }
}
